services:

    embaNET-intranet-workspace:

        container_name: embaNET-intranet-workspace

        image: softwareshinobi/embanet-intranet-workspace

        build: 

            context: .

            dockerfile: Dockerfile

        ports:

            - 8080:80
